### PR TITLE
Handle overwriting config setting with unescaped falresolverr url in env var

### PR DESCRIPTION
**Pull request by schroda**

### CODE REVIEW

**Comment by Syer10** [comment]
Can you update the docker-conpose example as well?

**Comment by schroda** [comment]
> Can you update the docker-conpose example as well?

done

**Comment by Syer10** [comment]
Hmm, what about people who set FlareSolverrUrl with escaped urls? Would it be possible to support both at least for a while?

**Comment by schroda** [comment]
this works with both

**Pull request merged**
